---
# tasks file for nginx

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install required software
  apt: name={{ item }} state=present
  with_items:
    - nginx

- name: NGINX config from default
  template:
    src: ~/wordpress-ansible/roles/nginx/templates/default
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx
