--- #Time to start)
#- hosts: mysql
#  remote_user: ansible
#  become: yes
#  become_method: sudo
#  connection: ssh
#  gather_facts: yes
#  vars_files:  
#    - /home/ansible/wordpress-ansible/global_vars.yml 
#  roles:
#    - mysql

- hosts: apache
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars_files:
    - /home/ansible/wordpress-ansible/global_vars.yml
  roles:
    - apache

#- hosts: nginx
#  remote_user: ansible
#  become: yes
#  become_method: sudo
#  connection: ssh
#  gather_facts: yes
#  roles:
#    - nginx


