---
# tasks file for apache
- name: Update default Apache site
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Update default Apache site port to 8081
  lineinfile:
    dest=/etc/apache2/ports.conf
    regexp="^Listen 80"
    line="Listen 8081"
  notify:
    - restart apache

#- name: Update default Apache Virtualhost port to 8081
#  lineinfile:
#    dest=/etc/apache2/sites-available/000-default.conf
#    regexp="^<VirtualHost \*:80>"
#    line="<VirtualHost *:8081>"
#  notify:
#    - restart apache


