---
# tasks file for apache
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install required software
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - python-mysqldb
    - php-mysql
    - php
    - libapache2-mod-php
    - mcrypt


- name: Update default Apache site port to 8081
  lineinfile:
    dest=/etc/apache2/ports.conf
    regexp="^Listen 80"
    line="Listen 8081"
  notify:
    - restart apache

- name: Apache 000 config 
  template:
    src: ~/wordpress-ansible/roles/apache/templates/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify:
    - restart apache


- name: Download WP
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

- name: Update WordPress config file
  lineinfile:
    dest=/var/www/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
    - {'regexp': "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_HOST', '{{groups['mysql'][0]}}');"}


- name: Query test
  command: mysql -h {{groups['mysql'][0]}} -u {{ wp_mysql_user }} -p{{ wp_mysql_password }} -e "INSERT INTO {{ wp_mysql_db }}.wp_users (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES ('{{item}}', 'user{{item}}', MD5('demo'), 'Your Name', 'test{{item}}@yourdomain.com', 'http://www.test.com/', '2011-06-07 00:00:00', '', '0', 'Your Name');"
  with_items:
    - 6
    - 7
    - 8
